### ISSUE TITLE
Feature request: encrypt between frame X and Y"

### ISSUE THREAD

**Issue by kaddy22** [Potomac/cryptimage#2]
Hello!

A very interesting program!

Often in the past (german TV Channel Premiere/Syster) the last seconds from a movie were unencryted so a „end encryption at frame“ or „encrypt between frame x and y“ option would be nice.
Is it possible to implement this feature in a next version?
THX for this program!

**Comment by Potomac** [comment]
Hello,

interesting idea, it's possible to implement it, but it require some adaptation for the other slider "no of frames" at the audio/video tab, in order to avoid conflict between sliders on the GUI,

I'm gonna think about it.

Thanks

**Comment by Potomac** [comment]
This feature is now implemented, in 1.8.0 version of cryptimage.
